framework:
    cache:
        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(resolve:REDIS_URL)%'

        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system