AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'storage/**/*'

Documentation:
  Enabled: false
