# Development environment override
services:
  php:
    build:
      context: .
      target: dev
    volumes:
      - ./:/site
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      APP_ENV: dev
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: ""
      RR_CONFIG: ".rr.dev.yaml"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  database:
    ports:
      - 5432:5432

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1080:1080"]
###< symfony/mailer ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
