#!/bin/bash

case $1 in
  'cs') shift; php vendor/bin/php-cs-fixer fix "$@";;
  'stan') shift; php vendor/bin/phpstan "$@";;
  'migrate') shift; php bin/console doctrine:migrations:migrate --no-interaction "$@";;
  'seed') shift; php bin/console doctrine:fixtures:load --no-interaction "$@";;
  'console') shift; php bin/console "$@";;
  'composer') shift; composer "$@";;
  'server') shift; symfony server:start "$@";;
  *) php bin/console "$@";;
esac
